Introduce empty polis.config for development
If I strictly follow the current instructions in the README, I get this error:

    Error: Cannot find module './polis.config'

By adding this line, we make the out of the box dev experience slightly nicer.